server:
  port: 8000

jwt:
  secret: cloud_computing_2026_grow_access_secret_key

spring:
  application:
    name: gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Authorization"
              - "Content-Type"
            allowCredentials: true

      routes:
        # =====================
        # Auth Service - Public
        # =====================
        - id: user-service-auth
          uri: http://34.50.12.192:3030
          predicates:
            - Path=/auth/**

        # =====================
        # User Service - Auth Required
        # =====================
        - id: user-service-user
          uri: http://34.50.12.192:3030
          predicates:
            - Path=/user,/user/**

        # =====================
        # User Service - Internal
        # =====================
        - id: user-service-internal
          uri: http://34.50.12.192:3030
          predicates:
            - Path=/api/internal/v1/users,/api/internal/v1/users/**

        # =====================
        # Achievement Service
        # =====================
        - id: achievement-service
          uri: http://8.230.16.157:3002
          predicates:
            - Path=/achievements,/achievements/**

        - id: achievement-internal
          uri: http://8.230.16.157:3002
          predicates:
            - Path=/internal/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG